# https://travis-ci.org/tornadoweb/tornado
language: python
python:
    - 3.6

install:
    - pip install -r requirements/base.txt

script:
    - pylint TaskManager
    - pylint H4/example.py
    - pylint H4/wsgi.py

sudo: false

matrix:
fast_finish: true
