# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roadmaps',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('estimate', models.DateField()),
                ('state', models.CharField(choices=[('in_progress', 'In progress'), ('ready', 'Ready')], default='in_progress', max_length=11)),
                ('roadmap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Manager.Roadmap')),
            ],
            options={
                'ordering': ('state', 'estimate'),
                'db_table': 'tasks',
            },
        ),
    ]
