# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-21 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_added_created_field_to_Task_created_Scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
